# Generated by Django 4.2.4 on 2023-08-08 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Blogning nomi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog/images/', verbose_name='Blogning rasmi')),
                ('description', models.TextField(verbose_name='Blogning tavsifi')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name="To'liq ism")),
                ('email', models.EmailField(max_length=254, verbose_name='Email pochta')),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
        ),
        migrations.CreateModel(
            name='Review_for_business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon raqam')),
                ('company', models.CharField(max_length=40, verbose_name='Kompaniya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Loyiha nomi')),
                ('descriptions', models.TextField(verbose_name='Loyiha tavsifi')),
                ('power', models.CharField(max_length=40, verbose_name='Loyiha quvvati')),
                ('annual_productivity', models.CharField(max_length=40, verbose_name='Yillik hosildorlik')),
                ('amount_of_savings', models.IntegerField(verbose_name='Tejamkorlik miqdori')),
                ('image_1', models.ImageField(upload_to='project/images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project_category', verbose_name='Loyihaning Kategoriyasi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Mahsulot nomi')),
                ('price', models.IntegerField(verbose_name='Mahsulot narxi')),
                ('info', models.TextField(verbose_name='Mahsulot haqida')),
                ('descriptions', models.TextField(verbose_name='Mahsulot tavsifi')),
                ('image_1', models.FileField(upload_to='image/', verbose_name='Mahsulot 1 chi rasmi')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='image/', verbose_name='Mahsulot 2 chi rasmi')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='image/', verbose_name='Mahsulot 3 chi rasmi')),
                ('image_4', models.FileField(blank=True, null=True, upload_to='image/', verbose_name='Mahsulot 4 chi rasmi')),
                ('characteristic', models.TextField(verbose_name='Mahsulot xarakteri')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
